# Generated by Django 6.0.7 on 2026-09-20 12:32

from django.db import migrations
# Tables already exist as store_*; only ORM state changes.


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_storeconfig_currency'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
migrations.AlterModelTable(
            name='aboutconfig',
            table='store_aboutconfig',
        ),
        migrations.AlterModelTable(
            name='aboutstat',
            table='store_aboutstat',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='store_cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='store_cartitem',
        ),
        migrations.AlterModelTable(
            name='category',
            table='store_category',
        ),
        migrations.AlterModelTable(
            name='config',
            table='store_config',
        ),
        migrations.AlterModelTable(
            name='contactconfig',
            table='store_contactconfig',
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='store_contactmessage',
        ),
        migrations.AlterModelTable(
            name='faq',
            table='store_faq',
        ),
        migrations.AlterModelTable(
            name='feature',
            table='store_feature',
        ),
        migrations.AlterModelTable(
            name='heroconfig',
            table='store_heroconfig',
        ),
        migrations.AlterModelTable(
            name='notificationoutbox',
            table='store_notificationoutbox',
        ),
        migrations.AlterModelTable(
            name='order',
            table='store_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='store_orderitem',
        ),
        migrations.AlterModelTable(
            name='partner',
            table='store_partner',
        ),
        migrations.AlterModelTable(
            name='product',
            table='store_product',
        ),
        migrations.AlterModelTable(
            name='productfeatureconfig',
            table='store_productfeatureconfig',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='store_productimage',
        ),
        migrations.AlterModelTable(
            name='seoconfig',
            table='store_seoconfig',
        ),
        migrations.AlterModelTable(
            name='socialconfig',
            table='store_socialconfig',
        ),
        migrations.AlterModelTable(
            name='storeconfig',
            table='store_storeconfig',
        ),
        migrations.AlterModelTable(
            name='telegramconfig',
            table='store_telegramconfig',
        ),
        migrations.AlterModelTable(
            name='telegramnotificationsettings',
            table='store_telegramnotificationsettings',
        ),
        migrations.AlterModelTable(
            name='telegramsubscriber',
            table='store_telegramsubscriber',
        ),
        migrations.AlterModelTable(
            name='themeconfig',
            table='store_themeconfig',
        ),
            ],
            database_operations=[],
        ),
    ]
