"""Apply inbox/shop_slots.json → hero_shop.html + approved copy.

Run after calibrator Save, or when user says «готово».

Desk + mob come from the calibrator. Mob is NOT remapped from desk
unless mob slots are missing.
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(r"d:\Cursor\clothing_shop\themes\curated\shapes")
INBOX = OUT / "inbox"
APPROVED = OUT / "approved"
TPL = Path(r"d:\Cursor\clothing_shop\themes\curated\templates\partials")

SLOT_IDS = ("product-1", "product-2", "product-3", "catalog-cta")

DEFAULT = {
    "desk": {
        "art": [1024.0, 828.0],
        "slots": {
            "product-1": [520.0, 470.0, 100.0, 100.0],
            "product-2": [640.0, 455.0, 100.0, 100.0],
            "product-3": [760.0, 475.0, 100.0, 100.0],
            "catalog-cta": [560.0, 600.0, 220.0, 42.0],
        },
    },
    "mob": {
        "art": [390.0, 844.0],
        "slots": {
            "product-1": [36.0, 700.0, 72.0, 72.0],
            "product-2": [130.0, 712.0, 72.0, 72.0],
            "product-3": [224.0, 704.0, 72.0, 72.0],
            "catalog-cta": [70.0, 792.0, 200.0, 36.0],
        },
    },
}


def load_slots() -> dict:
    for path in (INBOX / "shop_slots.json", APPROVED / "shop_slots.json"):
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
            print(f"using {path}")
            return data
    print("using built-in defaults")
    return DEFAULT


def normalize_slots(raw: dict | None, defaults: dict) -> dict:
    slots = {k: list(v) for k, v in defaults.items()}
    if not isinstance(raw, dict):
        return slots
    for sid in SLOT_IDS:
        v = raw.get(sid)
        if isinstance(v, (list, tuple)) and len(v) >= 4:
            slots[sid] = [float(v[0]), float(v[1]), float(v[2]), float(v[3])]
    return slots


def pct_style(slot: list[float], art: list[float]) -> str:
    aw, ah = float(art[0]), float(art[1])
    x, y, w, h = (float(slot[0]), float(slot[1]), float(slot[2]), float(slot[3]))
    return (
        f"left:{100 * x / aw:.4f}%;"
        f"top:{100 * y / ah:.4f}%;"
        f"width:{100 * w / aw:.4f}%;"
        f"height:{100 * h / ah:.4f}%;"
    )


def tile_block(n: int, style: str) -> str:
    return (
        f"  {{% if forloop.counter == {n} %}}\n"
        f'  <a class="cu-hero-shop__tile" style="{style}"\n'
        f"     href=\"{{% url 'catalog' %}}"
        f"{{% if category.slug %}}?category={{{{ category.slug }}}}{{% endif %}}\">\n"
        f"    {{% if category|display_image %}}\n"
        f'      <img src="{{{{ category|display_image }}}}" alt="{{{{ category.name }}}}" '
        f'loading="lazy" decoding="async">\n'
        f"    {{% else %}}\n"
        f'      <span class="cu-hero-shop__ph" aria-hidden="true"></span>\n'
        f"    {{% endif %}}\n"
        f"  </a>\n"
        f"  {{% endif %}}"
    )


def mode_block(mode: str, art: list[float], slots: dict) -> str:
    s1 = pct_style(slots["product-1"], art)
    s2 = pct_style(slots["product-2"], art)
    s3 = pct_style(slots["product-3"], art)
    sc = pct_style(slots["catalog-cta"], art)
    parts = [
        f'<div class="cu-hero-shop cu-hero-shop--{mode}" aria-label="Categories">',
        "  {% with tiles=home_tiles|default:categories %}",
        "  {% for category in tiles %}",
        "  {% if forloop.counter <= 3 %}",
        tile_block(1, s1),
        tile_block(2, s2),
        tile_block(3, s3),
        "  {% endif %}",
        "  {% endfor %}",
        "  {% endwith %}",
        f'  <a class="cu-hero-shop__cta" style="{sc}" href="{{% url \'catalog\' %}}">'
        "{% trans \"View Catalog\" %}</a>",
        "</div>",
    ]
    return "\n".join(parts)


def main() -> None:
    data = load_slots()
    desk = data.get("desk") or DEFAULT["desk"]
    mob = data.get("mob") or DEFAULT["mob"]

    desk_art = list(desk.get("art") or DEFAULT["desk"]["art"])
    mob_art = list(mob.get("art") or DEFAULT["mob"]["art"])

    desk_slots = normalize_slots(desk.get("slots"), DEFAULT["desk"]["slots"])
    mob_slots = normalize_slots(mob.get("slots"), DEFAULT["mob"]["slots"])

    html = (
        "{# shop overlay on C-dark-bottom — generated by _build_shop_overlay.py #}\n"
        "{% load product_media i18n %}\n"
        + mode_block("desk", desk_art, desk_slots)
        + "\n"
        + mode_block("mob", mob_art, mob_slots)
        + "\n"
    )
    TPL.mkdir(parents=True, exist_ok=True)
    dest = TPL / "hero_shop.html"
    dest.write_text(html, encoding="utf-8")
    print(f"wrote {dest}")

    payload = {
        "desk": {"art": desk_art, "slots": {k: list(desk_slots[k]) for k in SLOT_IDS}},
        "mob": {"art": mob_art, "slots": {k: list(mob_slots[k]) for k in SLOT_IDS}},
        "mob_from_desk": False,
        "saved_at": data.get("saved_at"),
    }
    text = json.dumps(payload, indent=2) + "\n"
    APPROVED.mkdir(parents=True, exist_ok=True)
    INBOX.mkdir(parents=True, exist_ok=True)
    (APPROVED / "shop_slots.json").write_text(text, encoding="utf-8")
    (INBOX / "shop_slots.json").write_text(text, encoding="utf-8")
    print("wrote approved + inbox (desk+mob from calibrator)")
    print("ok shop overlay")


if __name__ == "__main__":
    main()
